export const CREATE_RESTAURANT_REQUEST = "CREATE_RESTAURANT_REQUEST"
export const CREATE_RESTAURANT_SUCCESS = "CREATE_RESTAURANT_SUCCESS"
export const CREATE_RESTAURANT_FAILURE = "CREATE_RESTAURANT_FAILURE"

export const GET_ALL_RESTAURANTS_REQUEST = "GET_ALL_RESTAURANTS_REQUEST"
export const GET_ALL_RESTAURANTS_SUCCESS = "GET_ALL_RESTAURANTS_SUCCESS"
export const GET_ALL_RESTAURANTS_FAILURE = "GET_ALL_RESTAURANTS_FAILURE"

export const DELETE_RESTAURANT_REQUEST = "DELETE_RESTAURANT_REQUEST"
export const DELETE_RESTAURANT_SUCCESS = "DELETE_RESTAURANT_SUCCESS"
export const DELETE_RESTAURANT_FAILURE = "DELETE_RESTAURANT_FAILURE"

export const UPDATE_RESTAURANT_REQUEST = "UPDATE_RESTAURANT_REQUEST"
export const UPDATE_RESTAURANT_SUCCESS = "UPDATE_RESTAURANT_SUCCESS"
export const UPDATE_RESTAURANT_FAILURE = "UPDATE_RESTAURANT_FAILURE"

export const ADD_TO_FAVORITE_REQUEST = "ADD_TO_FAVORITE_REQUEST"
export const ADD_TO_FAVORITE_SUCCESS = "ADD_TO_FAVORITE_SUCCESS"
export const ADD_TO_FAVORITE_FAILURE = "ADD_TO_FAVORITE_FAILURE"

export const GET_RESTAURANT_BY_ID_REQUEST = "GET_RESTAURANT_BY_ID_REQUEST"
export const GET_RESTAURANT_BY_ID_SUCCESS = "GET_RESTAURANT_BY_ID_SUCCESS"
export const GET_RESTAURANT_BY_ID_FAILURE = "GET_RESTAURANT_BY_ID_FAILURE"

export const GET_RESTAURANT_BY_USER_ID_REQUEST = "GET_RESTAURANT_BY_USER_ID_REQUEST"
export const GET_RESTAURANT_BY_USER_ID_SUCCESS = "GET_RESTAURANT_BY_USER_ID_SUCCESS"
export const GET_RESTAURANT_BY_USER_ID_FAILURE = "GET_RESTAURANT_BY_USER_ID_FAILURE"

export const UPDATE_RESTAURANT_STATUS_REQUEST = "UPDATE_RESTAURANT_STATUS_REQUEST"
export const UPDATE_RESTAURANT_STATUS_SUCCESS = "UPDATE_RESTAURANT_STATUS_SUCCESS"
export const UPDATE_RESTAURANT_STATUS_FAILURE = "UPDATE_RESTAURANT_STATUS_FAILURE"

export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST"
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS"
export const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE"

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST"
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS"
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE"

export const GET_RESTAURANT_EVENTS_REQUEST = "GET_RESTAURANT_EVENTS_REQUEST"
export const GET_RESTAURANT_EVENTS_SUCCESS = "GET_RESTAURANT_EVENTS_SUCCESS"
export const GET_RESTAURANT_EVENTS_FAILURE = "GET_RESTAURANT_EVENTS_FAILURE"

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST"
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS"
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE"

export const GET_RESTAURANT_CATEGORY_REQUEST = "GET_RESTAURANT_CATEGORY_REQUEST"
export const GET_RESTAURANT_CATEGORY_SUCCESS = "GET_RESTAURANT_CATEGORY_SUCCESS"
export const GET_RESTAURANT_CATEGORY_FAILURE = "GET_RESTAURANT_CATEGORY_FAILURE"

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST"
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS"
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE"


export const LOGOUT = "LOGOUT"

export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST"
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS"
export const CREATE_EVENT_FAILURE = "CREATE_EVENT_FAILURE"

export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST"
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS"
export const UPDATE_EVENT_FAILURE = "UPDATE_EVENT_FAILURE"

export const BOOK_EVENT_REQUEST = "BOOK_EVENT_REQUEST"
export const BOOK_EVENT_SUCCESS = "BOOK_EVENT_SUCCESS"
export const BOOK_EVENT_FAILURE = "BOOK_EVENT_FAILURE"

export const GET_CUSTOMER_EVENTS_REQUEST = "GET_CUSTOMER_EVENTS_REQUEST"
export const GET_CUSTOMER_EVENTS_SUCCESS = "GET_CUSTOMER_EVENTS_SUCCESS"
export const GET_CUSTOMER_EVENTS_FAILURE = "GET_CUSTOMER_EVENTS_FAILURE"

export const UPDATE_EVENT_STATUS_REQUEST = "UPDATE_EVENT_STATUS_REQUEST"
export const UPDATE_EVENT_STATUS_SUCCESS = "UPDATE_EVENT_STATUS_SUCCESS"
export const UPDATE_EVENT_STATUS_FAILURE = "UPDATE_EVENT_STATUS_FAILURE"
