spring.application.name=craveo

server.port=8081

# DATABASE CONFIG (FIXED)
spring.datasource.url=jdbc:mysql://localhost:3306/craveo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Yuvi2411@jind
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=craveo-secure-key-1234567890-abcdefghijklmnopqrstuvwxyz

# STRIPE
stripe.api.key=sk_test_dummy_key

# FRONTEND URL
#frontend.url=http://localhost:5174
frontend.url=https://9t14rxjr-5174.inc1.devtunnels.ms/

